name: CI

on: [push, pull_request]

jobs:
  build:
    name: Build and test

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.9.x'
    - name: Build and test
      run: |
        flutter pub get
        flutter test
